### ISSUE TITLE
Django

### ISSUE THREAD

**Issue by JihyeHaley** [JihyeHaley/TIL#7]
still feel difficult to say Django.... :) 
Hope to be familiar with Django Framework ASAP

**Comment by suhailpgm** [comment]
just explore through every possible areas of django atleast once(by watching tutorial or other resources).and after, you'll like django very much.. it's really powerfull!

**Comment by JihyeHaley** [comment]
I already checked the documentation provided by Django.. But i still say D- jango.. I think it is common issues to everyone who are beginners of studying django ;)
